name: Linting and Validation

on: [pull_request]

jobs:
  validate-whitepaper:
    name: Validate Whitepaper
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - uses: pre-commit/action@v2.0.3
      name: "Linters and formatters check"
      with:
        extra_args: --all-files --show-diff-on-failure
